/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tela;

import Persistencia.SalaPersistencia;
import entidades.Sala;
import javax.swing.JOptionPane;

/**
 *
 * @author d4nny
 */
public class TelaSala extends javax.swing.JFrame {

    /**
     * Creates new form TelaSala
     */
    public TelaSala() {
        setTitle("Sala");
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNomeSala = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Excluir = new javax.swing.JButton();
        jButtonAtualizar = new javax.swing.JButton();
        jButtonRecupera = new javax.swing.JButton();
        jButtonSalva = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNomeSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeSalaActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome da Sala:");

        Excluir.setText("Excluir");
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });

        jButtonAtualizar.setText("Atualizar");
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });

        jButtonRecupera.setText("Recuperar");
        jButtonRecupera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRecuperaActionPerformed(evt);
            }
        });

        jButtonSalva.setText("Salvar");
        jButtonSalva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Excluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAtualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRecupera)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSalva)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtNomeSala, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalva, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRecupera, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        // TODO add your handling code here:
        // Recupera o nome da sala digitado no campo de texto
        String nomeSala = txtNomeSala.getText();

        // Chama o método para excluir a sala do banco de dados
        SalaPersistencia.excluir(nomeSala);

        // Exibe uma mensagem de que a sala foi excluída
        JOptionPane.showMessageDialog(null, "Sala excluída com sucesso!");

    }//GEN-LAST:event_ExcluirActionPerformed

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        // TODO add your handling code here:
        // Recupera o nome original da sala digitado no campo de texto
        String nomeOriginal = txtNomeSala.getText();

        // Recupera o novo nome da sala digitado em uma janela de entrada
        String novoNome = JOptionPane.showInputDialog(this, "Digite o novo nome da sala:", "Atualizar Sala", JOptionPane.QUESTION_MESSAGE);

        // Verifica se o novo nome foi fornecido
        if (novoNome != null && !novoNome.isEmpty()) {
            // Cria um objeto Sala com o novo nome
            Sala novaSala = new Sala(novoNome);

            // Chama o método para atualizar a sala no banco de dados
            SalaPersistencia.atualizar(nomeOriginal, novaSala);
        } else {
            // Se o novo nome não foi fornecido, exibe uma mensagem indicando que a operação foi cancelada
            JOptionPane.showMessageDialog(this, "Operação de atualização cancelada. O novo nome não foi fornecido.", "Operação Cancelada", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    private void jButtonRecuperaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRecuperaActionPerformed
        // TODO add your handling code here:
        // Recupera o nome da sala digitado no campo de texto
        String nomeSala = txtNomeSala.getText();

        // Chama o método para recuperar a sala do banco de dados
        Sala salaRecuperada = SalaPersistencia.recuperar(nomeSala);

        // Verifica se a sala foi encontrada
        if (salaRecuperada != null) {
            // Se encontrada, exiba os detalhes da sala em algum lugar, como uma caixa de diálogo ou uma área de texto
            JOptionPane.showMessageDialog(this, "Sala encontrada:\n" + salaRecuperada.toString(), "Sala Recuperada", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Se não encontrada, exiba uma mensagem indicando que a sala não foi encontrada
            JOptionPane.showMessageDialog(this, "Sala não encontrada.", "Sala Não Encontrada", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonRecuperaActionPerformed

    private void jButtonSalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvaActionPerformed
        // Recupera o nome da sala digitado no campo de texto
        String nomeSala = txtNomeSala.getText();

        // Cria um objeto Sala com o nome recuperado
        Sala sala = new Sala(nomeSala);

        // Chama o método para salvar a sala no banco de dados
        SalaPersistencia.salvar(sala);

        // Verifica se a sala foi salva com sucesso
        if (SalaPersistencia.recuperar(nomeSala) != null) {
            JOptionPane.showMessageDialog(null, "Sala cadastrada com sucesso!");
        } else {
            JOptionPane.showMessageDialog(null, "Falha ao cadastrar sala.");
        }

    }//GEN-LAST:event_jButtonSalvaActionPerformed

    private void txtNomeSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeSalaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSala().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Excluir;
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonRecupera;
    private javax.swing.JButton jButtonSalva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNomeSala;
    // End of variables declaration//GEN-END:variables
}
